### ISSUE TITLE
Essayer Hugo pour la génération du site à partir de fichiers .md

### ISSUE THREAD

**Issue by toopy** [les-bacots/les-bacots.github.io#1]
Utiliser des fichiers .md pour la gestion versionnée de contenu semble une piste intéressante.

Une arborescence de fichiers .md peut ensuite facilement être utilisé pour la génération d'un site avec un thème.

Cette mise à jour peut être faite avec l'outil d'intégration continu de Gitlab. Le résultat tant qu'il reste simple peut lui aussi être hébergé par Gitlab:

- https://gohugo.io/
- https://gohugo.io/hosting-and-deployment/hosting-on-gitlab/

Let's try this!

**Comment by simenca** [comment]
J'imagine quoi doit pouvoir fermer cette issue maintenant (si ca ne se fait pas de façon automatique après un merge).
