### ISSUE TITLE
Renomer la section Thématiques en "Groupes de Travail"

### ISSUE THREAD

**Issue by simenca** [les-bacots/les-bacots.github.io#5]

**Comment by toopy** [comment]
Comme la contribution est en revue (cf. #2) on peut demander un changement dans le contribution en cours.

**Comment by simenca** [comment]
Ok. Est-ce qu'il y a moyen de merger une issue en comment sur un ticket existant? Désolé si je fou un peu le bordel mais j'essai de m'approprier le truc. Maintenant je trovue que la rédac dans les ticket est plutot simple donc est ce que ca ne pourrait pas être dans ces objets que les contributions seront faites directement?

**Comment by toopy** [comment]
Pas de souci. On peut mettre des liens au pire. Côté contribution (pull requests) on peut commenter pareil.
