### ISSUE TITLE
Créer le profil Membre : Margaux de Roquefeuil

### ISSUE THREAD

**Issue by simenca** [les-bacots/les-bacots.github.io#55]
### Margaux de Roquefeuil
Profession:  *A compléter*

### Qui suis je?

- **A compléter obligatoire**

Mes intérêts sur Bois-Le-Roi et en Seine-et-Marne

- **A compléter obligatoire**

### Participation à la vie locale de Bois-le-Roi

- **A compléter obligatoire**

### Ma profession actuelle

- **A compléter obligatoire**

### Mes expériences passées

- *A compléter option*

### Ma formation

-  *A compléter option*

### Mes hobbies & passions

- *A compléter option*

**Comment by MargauxdeR** [comment]
> 



> test

**Comment by MargauxdeR** [comment]
Une fois a que je suis là comment je complète ma fiche profil please ? 😅

**Comment by simenca** [comment]
En fait soit tu complètes dans ce ticket dans les commentaires ici et on fera la copie ensuite sur la
Page une fois complétée... soit comme la page existe déjà tu peux aller sur le site les-bacots.GitHub.io et tu peux directement éditer (pas sur mais un peu plus tech il faudrait que je te montre une premier fois)

**Comment by MargauxdeR** [comment]
Profession : Directrice adjointe Bureau d’Etudes Travaux Publics

qui suis-Je ?

Margaux, arrivée à Bois le Roi il y a 5 ans. Nous nous sommes installés ici avec nos 4 enfants très vite après avoir été séduits par la qualité de vie hors pair de Bois le Roi entre Seine et forêt.

Participation à la vie locale : je ne participe à aucune association mais nous sommes très heureux de profiter de la richesse des associations locales, et notamment en terme de sport et de musique.  J’ai tout de suite voulu m’impliquer dans cette initiative car le développement de Bois le Roi apparaît comme un enjeu majeur pour notre avenir et je suis convaincue que chacun a beaucoup à y apporter !

**Comment by MargauxdeR** [comment]
Good ?

**Comment by simenca** [comment]
Salut Margaux,

Ca me parait très bien. Faut peut être juste ajouter la rue où tu habites à BLR, on l'a tous mis et je pense que c'est important aussi pour la compréhension.

Et je vais t'embêter encore un peu est ce que tu pourrais tester la création du profil via la demande template qu'on a créé hier soir https://github.com/les-bacots/les-bacots.github.io/issues/new/choose faut juste que tu reprennes les mêmes éléments en créant un nouveau ticket
