### ISSUE TITLE
Créer le profil Membre : Géraud Talandier

### ISSUE THREAD

**Issue by simenca** [les-bacots/les-bacots.github.io#56]
### Géraud Talandier
Profession:  *A compléter*

### Qui suis je?

- **A compléter obligatoire**

Mes intérêts sur Bois-Le-Roi et en Seine-et-Marne

- **A compléter obligatoire**

### Participation à la vie locale de Bois-le-Roi

- **A compléter obligatoire**

### Ma profession actuelle

- **A compléter obligatoire**

### Mes expériences passées

- *A compléter option*

### Ma formation

-  *A compléter option*

### Mes hobbies & passions

- *A compléter option*

**Comment by GeroLauvergnat** [comment]
# Géraud Talandier

Profession: Spécialiste des moyens de payements

### Qui suis je?

    Installé à Bois le Roi depuis plus de 20 ans, j'y ai élevé 4 enfants et, comme au premier jour.

### Mes intérêts sur Bois-Le-Roi et en Seine-et-Marne

    Je suis heureux de vivre dans un environnement aussi verdoyant et paisible en étant aussi proche de Paris.

### Participation à la vie locale de Bois-le-Roi

    Soutien scolaire à Bois le Roi.
    Sinon, je suis plutôt un consommateur des ressources locales (commerces, cultures, sports...)

### Ma profession actuelle

    Gestionnaire de projets informatiques dans le secteur de la banque et la finance depuis 40 ans,

### Mes expériences passées

    Citybank, Bourse de Paris, Insead, HSBC, Société Générale, Oney Bank, BCE, Banque de France...

### Ma formation

    Ingénieur (informatique), MBA (finance à Washington) et Insead

### Mes hobbies & passions

    La marche en forêt
    Divers sports : VTT, Ski, voile, aviron...
    Du chant choral
    La programmation informatique
