### ISSUE TITLE
Demande de création de profil Membre pour Pierrick Houdeville

### ISSUE THREAD

**Issue by PHoudeville77** [les-bacots/les-bacots.github.io#65]
**Nom et Prénom :**
Houdeville Pierrick

**Profession : **
Consultant 

**Qui êtes-vous?**
- bacot depuis 2013, marié et père de 3 garçons

**Quels sont vos intérêts sur Bois-le-Roi et en Seine-et-Marne?**
- je suis propriétaire d'une maison rue des Foucherolles

**Participez vous à la vie locale de Bois-le-Roi?**
- aucun rôle associatif jusqu'à présent et l'initiative les-bacots.org

**Quelle est votre profession actuelle?**
- Consultant en organisation pour les directions financières sur des sujets de pilotage de la performance (conso, reporting, contrôle de gestion), depuis une quinzaine d'années

**Comment by simenca** [comment]
Dans vie locale, j'ai mis ca également pour bien clarifier notre rôle aussi sur cette première action : 

- J’ai aidé l’association “Bien à Bois-le-Roi” à collecter des fonds en organisant la collecte de crowdfunding sur HelloAsso (https://www.helloasso.com/associations/bien-a-bois-le-roi/collectes/collecte-1-bien-a-bois-le-roi) et soutenu en tant que donateur.
